import {
  BlockTimeSchema,
  type CostCenter,
  CostCenterSchema,
  type DocumentRecord,
  DocumentRecordSchema,
  type Equipment,
  EquipmentSchema,
  type HospitalDashboardData,
  HospitalSchema,
  type MessageThread,
  MessageThreadSchema,
  type Notification,
  NotificationSchema,
  type IntegrationSetting,
  IntegrationSettingSchema,
  type OverviewMetric,
  OverviewMetricSchema,
  OperatingRoomSchema,
  type PreferenceCard,
  PreferenceCardSchema,
  type StaffMember,
  StaffMemberSchema,
  type Surgeon,
  SurgeonSchema,
  type SurgeryCase,
  SurgeryCaseSchema,
  type WaitlistEntry,
  WaitlistEntrySchema,
  type Conflict,
  ConflictSchema,
} from "@/lib/validations/smartor";

const hospitals = HospitalSchema.array().parse([
  {
    id: "hospital-north-harbor",
    slug: "north-harbor",
    name: "North Harbor Medical Center",
    city: "Seattle",
    state: "WA",
    networkName: "Cascade Surgical Alliance",
    beds: 264,
    orCount: 5,
    occupancyRate: 91,
    onTimeStarts: 88,
    turnoverMinutes: 34,
    alertsOpen: 3,
    ehrStatus: "Connected",
    adoptionScore: 93,
  },
  {
    id: "hospital-st-catherine-west",
    slug: "st-catherine-west",
    name: "St. Catherine West Pavilion",
    city: "Austin",
    state: "TX",
    networkName: "Cascade Surgical Alliance",
    beds: 188,
    orCount: 5,
    occupancyRate: 86,
    onTimeStarts: 82,
    turnoverMinutes: 38,
    alertsOpen: 5,
    ehrStatus: "Sandbox",
    adoptionScore: 89,
  },
]);

const surgeons = SurgeonSchema.array().parse([
  {
    id: "surgeon-nh-asha-raman",
    hospitalSlug: "north-harbor",
    name: "Dr. Asha Raman",
    specialty: "Orthopedic Reconstruction",
    blockPreference: "Mon / Thu morning block",
    availability: [
      { day: "Today", start: "07:00", end: "15:30", note: "Robotics backup at 14:00" },
      { day: "Tomorrow", start: "08:00", end: "13:00" },
    ],
  },
  {
    id: "surgeon-nh-miguel-alvarez",
    hospitalSlug: "north-harbor",
    name: "Dr. Miguel Alvarez",
    specialty: "Cardiac Surgery",
    blockPreference: "Tue / Fri all-day block",
    availability: [
      { day: "Today", start: "07:30", end: "17:00", note: "Perfusion review at 12:15" },
      { day: "Tomorrow", start: "09:00", end: "14:00" },
    ],
  },
  {
    id: "surgeon-nh-priya-desai",
    hospitalSlug: "north-harbor",
    name: "Dr. Priya Desai",
    specialty: "General & Endocrine Surgery",
    blockPreference: "Wed afternoon block",
    availability: [
      { day: "Today", start: "09:30", end: "18:00", note: "Clinic handoff at 16:30" },
      { day: "Tomorrow", start: "07:00", end: "11:30" },
    ],
  },
  {
    id: "surgeon-sc-julia-bennett",
    hospitalSlug: "st-catherine-west",
    name: "Dr. Julia Bennett",
    specialty: "Neurosurgery",
    blockPreference: "Mon / Wed cranial block",
    availability: [
      { day: "Today", start: "06:45", end: "14:00", note: "Tumor board at 15:00" },
      { day: "Tomorrow", start: "08:00", end: "16:00" },
    ],
  },
  {
    id: "surgeon-sc-omar-farouk",
    hospitalSlug: "st-catherine-west",
    name: "Dr. Omar Farouk",
    specialty: "General Surgery",
    blockPreference: "Tue / Thu acute care block",
    availability: [
      { day: "Today", start: "07:00", end: "19:00", note: "On emergency call" },
      { day: "Tomorrow", start: "08:30", end: "15:00" },
    ],
  },
  {
    id: "surgeon-sc-elena-novak",
    hospitalSlug: "st-catherine-west",
    name: "Dr. Elena Novak",
    specialty: "Gynecologic Surgery",
    blockPreference: "Fri women’s health block",
    availability: [
      { day: "Today", start: "08:00", end: "17:30", note: "Two urgent consults pending" },
      { day: "Tomorrow", start: "10:00", end: "16:30" },
    ],
  },
]);

const staff = StaffMemberSchema.array().parse([
  {
    id: "staff-nh-ava-clark",
    hospitalSlug: "north-harbor",
    name: "Ava Clark",
    role: "Charge RN",
    shift: "07:00 - 19:00",
    assignedRoomId: "room-nh-or-1",
    availabilityLabel: "Locked to OR 1 coverage",
  },
  {
    id: "staff-nh-liam-brooks",
    hospitalSlug: "north-harbor",
    name: "Liam Brooks",
    role: "Anesthesiologist",
    shift: "07:00 - 17:00",
    assignedRoomId: "room-nh-or-2",
    availabilityLabel: "Perfusion consult overlap at 11:30",
  },
  {
    id: "staff-nh-sofia-nash",
    hospitalSlug: "north-harbor",
    name: "Sofia Nash",
    role: "Scrub Tech",
    shift: "08:00 - 16:00",
    assignedRoomId: "room-nh-or-4",
    availabilityLabel: "Available after turnover",
  },
  {
    id: "staff-nh-daniel-yu",
    hospitalSlug: "north-harbor",
    name: "Daniel Yu",
    role: "Sterile Processing Lead",
    shift: "06:30 - 15:30",
    assignedRoomId: null,
    availabilityLabel: "Covering implant tray rush order",
  },
  {
    id: "staff-sc-zoe-hart",
    hospitalSlug: "st-catherine-west",
    name: "Zoe Hart",
    role: "Charge RN",
    shift: "07:00 - 19:00",
    assignedRoomId: "room-sc-or-1",
    availabilityLabel: "Neuro room escalation point",
  },
  {
    id: "staff-sc-noah-wells",
    hospitalSlug: "st-catherine-west",
    name: "Noah Wells",
    role: "Anesthesiologist",
    shift: "07:00 - 17:00",
    assignedRoomId: "room-sc-or-2",
    availabilityLabel: "Float backup after 13:00",
  },
  {
    id: "staff-sc-kira-mills",
    hospitalSlug: "st-catherine-west",
    name: "Kira Mills",
    role: "OR Scheduler",
    shift: "06:00 - 14:00",
    assignedRoomId: null,
    availabilityLabel: "Monitoring emergency inserts",
  },
  {
    id: "staff-sc-isaac-porter",
    hospitalSlug: "st-catherine-west",
    name: "Isaac Porter",
    role: "Circulating RN",
    shift: "09:00 - 21:00",
    assignedRoomId: "room-sc-or-4",
    availabilityLabel: "Room turnover support at 12:15",
  },
]);

const rooms = OperatingRoomSchema.array().parse([
  {
    id: "room-nh-or-1",
    hospitalSlug: "north-harbor",
    name: "OR 1",
    serviceLine: "Orthopedics",
    status: "In Surgery",
    activeCaseId: "case-nh-1",
    nextCaseId: "case-nh-4",
    utilizationRate: 94,
    turnoverMinutes: 29,
    staffedBy: ["staff-nh-ava-clark"],
  },
  {
    id: "room-nh-or-2",
    hospitalSlug: "north-harbor",
    name: "OR 2",
    serviceLine: "Cardiac",
    status: "Pre-op",
    activeCaseId: "case-nh-2",
    utilizationRate: 88,
    turnoverMinutes: 41,
    staffedBy: ["staff-nh-liam-brooks"],
  },
  {
    id: "room-nh-or-3",
    hospitalSlug: "north-harbor",
    name: "OR 3",
    serviceLine: "General Surgery",
    status: "Available",
    nextCaseId: "case-nh-5",
    utilizationRate: 76,
    turnoverMinutes: 32,
    staffedBy: [],
  },
  {
    id: "room-nh-or-4",
    hospitalSlug: "north-harbor",
    name: "OR 4",
    serviceLine: "General Surgery",
    status: "Turnover",
    activeCaseId: "case-nh-3",
    utilizationRate: 85,
    turnoverMinutes: 44,
    staffedBy: ["staff-nh-sofia-nash"],
  },
  {
    id: "room-nh-or-5",
    hospitalSlug: "north-harbor",
    name: "OR 5",
    serviceLine: "Flex / Add-on",
    status: "Delayed",
    utilizationRate: 51,
    turnoverMinutes: 47,
    staffedBy: [],
  },
  {
    id: "room-sc-or-1",
    hospitalSlug: "st-catherine-west",
    name: "OR 1",
    serviceLine: "Neurosurgery",
    status: "In Surgery",
    activeCaseId: "case-sc-1",
    nextCaseId: "case-sc-6",
    utilizationRate: 92,
    turnoverMinutes: 36,
    staffedBy: ["staff-sc-zoe-hart"],
  },
  {
    id: "room-sc-or-2",
    hospitalSlug: "st-catherine-west",
    name: "OR 2",
    serviceLine: "Acute Care",
    status: "Pre-op",
    activeCaseId: "case-sc-2",
    utilizationRate: 83,
    turnoverMinutes: 39,
    staffedBy: ["staff-sc-noah-wells"],
  },
  {
    id: "room-sc-or-3",
    hospitalSlug: "st-catherine-west",
    name: "OR 3",
    serviceLine: "Women’s Health",
    status: "Available",
    nextCaseId: "case-sc-3",
    utilizationRate: 78,
    turnoverMinutes: 31,
    staffedBy: [],
  },
  {
    id: "room-sc-or-4",
    hospitalSlug: "st-catherine-west",
    name: "OR 4",
    serviceLine: "Spine",
    status: "Turnover",
    activeCaseId: "case-sc-4",
    utilizationRate: 81,
    turnoverMinutes: 43,
    staffedBy: ["staff-sc-isaac-porter"],
  },
  {
    id: "room-sc-or-5",
    hospitalSlug: "st-catherine-west",
    name: "OR 5",
    serviceLine: "Flex / Add-on",
    status: "Delayed",
    activeCaseId: "case-sc-5",
    utilizationRate: 62,
    turnoverMinutes: 48,
    staffedBy: [],
  },
]);

const equipment = EquipmentSchema.array().parse([
  {
    id: "equip-nh-robotic-knee",
    hospitalSlug: "north-harbor",
    name: "Robotic Knee Console",
    type: "Robotics",
    status: "In Use",
    assignedCaseId: "case-nh-1",
    lastSterilizedAt: "06:42",
  },
  {
    id: "equip-nh-perfusion-pump",
    hospitalSlug: "north-harbor",
    name: "Perfusion Pump 2",
    type: "Cardiac Support",
    status: "Reserved",
    assignedCaseId: "case-nh-2",
    lastSterilizedAt: "05:58",
  },
  {
    id: "equip-nh-lap-tower",
    hospitalSlug: "north-harbor",
    name: "Laparoscopy Tower A",
    type: "Endoscopy",
    status: "Ready",
    assignedCaseId: "case-nh-5",
    lastSterilizedAt: "07:08",
  },
  {
    id: "equip-nh-implant-tray",
    hospitalSlug: "north-harbor",
    name: "Revision Hip Implant Tray",
    type: "Implants",
    status: "Sterilizing",
    assignedCaseId: "case-nh-4",
    lastSterilizedAt: "08:31",
  },
  {
    id: "equip-sc-neuro-navigation",
    hospitalSlug: "st-catherine-west",
    name: "Neuro Navigation Cart",
    type: "Navigation",
    status: "In Use",
    assignedCaseId: "case-sc-1",
    lastSterilizedAt: "06:25",
  },
  {
    id: "equip-sc-fluoro",
    hospitalSlug: "st-catherine-west",
    name: "Mobile C-Arm",
    type: "Imaging",
    status: "Reserved",
    assignedCaseId: "case-sc-4",
    lastSterilizedAt: "07:12",
  },
  {
    id: "equip-sc-lap-tower",
    hospitalSlug: "st-catherine-west",
    name: "Acute Care Laparoscopy Tower",
    type: "Endoscopy",
    status: "Ready",
    assignedCaseId: "case-sc-2",
    lastSterilizedAt: "07:35",
  },
  {
    id: "equip-sc-fetal-monitor",
    hospitalSlug: "st-catherine-west",
    name: "Fetal Monitoring Hub",
    type: "Women’s Health",
    status: "Maintenance",
    assignedCaseId: null,
    lastSterilizedAt: "Yesterday",
  },
]);

const cases = SurgeryCaseSchema.array().parse([
  {
    id: "case-nh-1",
    hospitalSlug: "north-harbor",
    patientName: "Maria Chen",
    procedureName: "Total Knee Arthroplasty",
    surgeonId: "surgeon-nh-asha-raman",
    operatingRoomId: "room-nh-or-1",
    scheduledStart: "07:15",
    estimatedMinutes: 135,
    predictedMinutes: 142,
    actualMinutes: null,
    status: "In Surgery",
    urgency: "Elective",
    insuranceStatus: "Authorized",
    documentationStatus: "Complete",
    delayReason: null,
    staffIds: ["staff-nh-ava-clark"],
    equipmentIds: ["equip-nh-robotic-knee"],
    preOpChecklist: [
      { label: "Consent signed", complete: true },
      { label: "Labs verified", complete: true },
      { label: "Antibiotics released", complete: true },
      { label: "Implant tray in room", complete: true },
    ],
  },
  {
    id: "case-nh-2",
    hospitalSlug: "north-harbor",
    patientName: "Samuel Ortiz",
    procedureName: "CABG x3",
    surgeonId: "surgeon-nh-miguel-alvarez",
    operatingRoomId: "room-nh-or-2",
    scheduledStart: "08:00",
    estimatedMinutes: 210,
    predictedMinutes: 225,
    actualMinutes: null,
    status: "Pre-op",
    urgency: "Urgent",
    insuranceStatus: "Authorized",
    documentationStatus: "In Review",
    delayReason: "Perfusion staffing handoff",
    staffIds: ["staff-nh-liam-brooks"],
    equipmentIds: ["equip-nh-perfusion-pump"],
    preOpChecklist: [
      { label: "Anesthesia clearance", complete: true },
      { label: "Blood products released", complete: true },
      { label: "ICU bed confirmed", complete: false },
      { label: "Family consent re-verified", complete: true },
    ],
  },
  {
    id: "case-nh-3",
    hospitalSlug: "north-harbor",
    patientName: "Lila Brooks",
    procedureName: "Laparoscopic Colectomy",
    surgeonId: "surgeon-nh-priya-desai",
    operatingRoomId: "room-nh-or-4",
    scheduledStart: "07:40",
    estimatedMinutes: 150,
    predictedMinutes: 165,
    actualMinutes: 173,
    status: "Turnover",
    urgency: "Urgent",
    insuranceStatus: "Pending",
    documentationStatus: "Complete",
    delayReason: "Unexpected adhesions increased case time",
    staffIds: ["staff-nh-sofia-nash"],
    equipmentIds: [],
    preOpChecklist: [
      { label: "Lab panel received", complete: true },
      { label: "Bowel prep complete", complete: true },
      { label: "Pathology pickup arranged", complete: true },
      { label: "PACU alert sent", complete: true },
    ],
  },
  {
    id: "case-nh-4",
    hospitalSlug: "north-harbor",
    patientName: "Owen Patel",
    procedureName: "Revision Hip Arthroplasty",
    surgeonId: "surgeon-nh-asha-raman",
    operatingRoomId: "room-nh-or-1",
    scheduledStart: "12:30",
    estimatedMinutes: 180,
    predictedMinutes: 194,
    actualMinutes: null,
    status: "Scheduled",
    urgency: "Elective",
    insuranceStatus: "Authorized",
    documentationStatus: "In Review",
    delayReason: null,
    staffIds: ["staff-nh-ava-clark", "staff-nh-daniel-yu"],
    equipmentIds: ["equip-nh-implant-tray"],
    preOpChecklist: [
      { label: "Implant consignment received", complete: false },
      { label: "Type & screen confirmed", complete: true },
      { label: "Special positioning posted", complete: true },
    ],
  },
  {
    id: "case-nh-5",
    hospitalSlug: "north-harbor",
    patientName: "Amelia Stone",
    procedureName: "Thyroid Lobectomy",
    surgeonId: "surgeon-nh-priya-desai",
    operatingRoomId: "room-nh-or-3",
    scheduledStart: "11:10",
    estimatedMinutes: 95,
    predictedMinutes: 103,
    actualMinutes: null,
    status: "Scheduled",
    urgency: "Elective",
    insuranceStatus: "Pending",
    documentationStatus: "Missing",
    delayReason: null,
    staffIds: ["staff-nh-sofia-nash"],
    equipmentIds: ["equip-nh-lap-tower"],
    preOpChecklist: [
      { label: "Ultrasound uploaded", complete: true },
      { label: "Nerve monitoring ready", complete: true },
      { label: "Pathology labels printed", complete: false },
    ],
  },
  {
    id: "case-nh-6",
    hospitalSlug: "north-harbor",
    patientName: "Noah Fisher",
    procedureName: "Emergency Appendectomy",
    surgeonId: "surgeon-nh-priya-desai",
    operatingRoomId: null,
    scheduledStart: "10:45",
    estimatedMinutes: 80,
    predictedMinutes: 88,
    actualMinutes: null,
    status: "Waitlist",
    urgency: "Emergent",
    insuranceStatus: "Pending",
    documentationStatus: "Missing",
    delayReason: "Awaiting room assignment",
    staffIds: ["staff-nh-liam-brooks"],
    equipmentIds: [],
    preOpChecklist: [
      { label: "CT reviewed", complete: true },
      { label: "Consent on chart", complete: true },
      { label: "Antibiotics started", complete: true },
    ],
  },
  {
    id: "case-sc-1",
    hospitalSlug: "st-catherine-west",
    patientName: "Harper Lee",
    procedureName: "Craniotomy for Tumor Resection",
    surgeonId: "surgeon-sc-julia-bennett",
    operatingRoomId: "room-sc-or-1",
    scheduledStart: "06:45",
    estimatedMinutes: 240,
    predictedMinutes: 258,
    actualMinutes: null,
    status: "In Surgery",
    urgency: "Urgent",
    insuranceStatus: "Authorized",
    documentationStatus: "Complete",
    delayReason: null,
    staffIds: ["staff-sc-zoe-hart"],
    equipmentIds: ["equip-sc-neuro-navigation"],
    preOpChecklist: [
      { label: "MRI registered", complete: true },
      { label: "Blood products available", complete: true },
      { label: "Neuronavigation calibrated", complete: true },
      { label: "ICU handoff ready", complete: true },
    ],
  },
  {
    id: "case-sc-2",
    hospitalSlug: "st-catherine-west",
    patientName: "Benicio Cruz",
    procedureName: "Laparoscopic Cholecystectomy",
    surgeonId: "surgeon-sc-omar-farouk",
    operatingRoomId: "room-sc-or-2",
    scheduledStart: "08:10",
    estimatedMinutes: 90,
    predictedMinutes: 96,
    actualMinutes: null,
    status: "Pre-op",
    urgency: "Urgent",
    insuranceStatus: "Authorized",
    documentationStatus: "Complete",
    delayReason: null,
    staffIds: ["staff-sc-noah-wells"],
    equipmentIds: ["equip-sc-lap-tower"],
    preOpChecklist: [
      { label: "Ultrasound confirmed", complete: true },
      { label: "Bloodwork complete", complete: true },
      { label: "Antibiotics started", complete: true },
      { label: "Post-op bed held", complete: false },
    ],
  },
  {
    id: "case-sc-3",
    hospitalSlug: "st-catherine-west",
    patientName: "Aaliyah King",
    procedureName: "Robotic Hysterectomy",
    surgeonId: "surgeon-sc-elena-novak",
    operatingRoomId: "room-sc-or-3",
    scheduledStart: "11:00",
    estimatedMinutes: 140,
    predictedMinutes: 150,
    actualMinutes: null,
    status: "Scheduled",
    urgency: "Elective",
    insuranceStatus: "Pending",
    documentationStatus: "In Review",
    delayReason: null,
    staffIds: ["staff-sc-isaac-porter"],
    equipmentIds: [],
    preOpChecklist: [
      { label: "Blood products not needed", complete: true },
      { label: "Robotic tray reserved", complete: true },
      { label: "Insurance auth finalized", complete: false },
    ],
  },
  {
    id: "case-sc-4",
    hospitalSlug: "st-catherine-west",
    patientName: "Ravi Shah",
    procedureName: "Lumbar Microdiscectomy",
    surgeonId: "surgeon-sc-julia-bennett",
    operatingRoomId: "room-sc-or-4",
    scheduledStart: "07:30",
    estimatedMinutes: 110,
    predictedMinutes: 122,
    actualMinutes: 129,
    status: "Turnover",
    urgency: "Elective",
    insuranceStatus: "Authorized",
    documentationStatus: "Complete",
    delayReason: "Fluoro downtime added 12 minutes",
    staffIds: ["staff-sc-isaac-porter"],
    equipmentIds: ["equip-sc-fluoro"],
    preOpChecklist: [
      { label: "Imaging uploaded", complete: true },
      { label: "Positioning pillows ready", complete: true },
      { label: "Pain service notified", complete: true },
    ],
  },
  {
    id: "case-sc-5",
    hospitalSlug: "st-catherine-west",
    patientName: "Fiona Morgan",
    procedureName: "Emergency Cesarean Section",
    surgeonId: "surgeon-sc-elena-novak",
    operatingRoomId: "room-sc-or-5",
    scheduledStart: "09:50",
    estimatedMinutes: 65,
    predictedMinutes: 72,
    actualMinutes: null,
    status: "Delayed",
    urgency: "Emergent",
    insuranceStatus: "Pending",
    documentationStatus: "Missing",
    delayReason: "Fetal monitoring hub still in maintenance",
    staffIds: ["staff-sc-noah-wells"],
    equipmentIds: [],
    preOpChecklist: [
      { label: "Blood bank notified", complete: true },
      { label: "NICU team on standby", complete: true },
      { label: "Monitoring hub verified", complete: false },
    ],
  },
  {
    id: "case-sc-6",
    hospitalSlug: "st-catherine-west",
    patientName: "David Kim",
    procedureName: "VP Shunt Revision",
    surgeonId: "surgeon-sc-julia-bennett",
    operatingRoomId: null,
    scheduledStart: "12:20",
    estimatedMinutes: 85,
    predictedMinutes: 94,
    actualMinutes: null,
    status: "Waitlist",
    urgency: "Urgent",
    insuranceStatus: "Authorized",
    documentationStatus: "In Review",
    delayReason: "Queued behind emergent OB add-on",
    staffIds: ["staff-sc-zoe-hart"],
    equipmentIds: [],
    preOpChecklist: [
      { label: "CT verified", complete: true },
      { label: "Pediatrics consult signed", complete: true },
      { label: "OR insert tray ready", complete: false },
    ],
  },
]);

const notifications = NotificationSchema.array().parse([
  {
    id: "note-nh-1",
    hospitalSlug: "north-harbor",
    level: "Critical",
    title: "Emergency add-on arrived from ED",
    detail: "Appendectomy patient is prepped and awaiting room assignment.",
    timestamp: "09:14",
  },
  {
    id: "note-nh-2",
    hospitalSlug: "north-harbor",
    level: "Watch",
    title: "Perfusion staffing overlap",
    detail: "OR 2 and OR 5 request the same perfusion support window at 11:30.",
    timestamp: "08:57",
  },
  {
    id: "note-nh-3",
    hospitalSlug: "north-harbor",
    level: "Info",
    title: "Room turnover accelerated",
    detail: "OR 4 is six minutes ahead of its expected clean and setup cycle.",
    timestamp: "08:41",
  },
  {
    id: "note-sc-1",
    hospitalSlug: "st-catherine-west",
    level: "Critical",
    title: "OB emergency board activated",
    detail: "OR 5 is holding for fetal monitoring hardware release.",
    timestamp: "09:22",
  },
  {
    id: "note-sc-2",
    hospitalSlug: "st-catherine-west",
    level: "Watch",
    title: "Neuro room overrun risk",
    detail: "Current craniotomy is trending 18 minutes above expected duration.",
    timestamp: "08:53",
  },
  {
    id: "note-sc-3",
    hospitalSlug: "st-catherine-west",
    level: "Info",
    title: "Late-day urgent case queued",
    detail: "VP shunt revision is queued for first available clean room after 12:20.",
    timestamp: "08:36",
  },
]);

const conflicts = ConflictSchema.array().parse([
  {
    id: "conflict-nh-1",
    hospitalSlug: "north-harbor",
    severity: "High",
    title: "Emergency appendectomy lacks clean room",
    detail: "Current room plan cannot accommodate the add-on without displacing the thyroid case.",
    recommendation: "Move thyroid lobectomy to OR 5 once sterilization completes, then insert appendectomy into OR 3.",
  },
  {
    id: "conflict-nh-2",
    hospitalSlug: "north-harbor",
    severity: "Medium",
    title: "Implant tray turnaround may delay revision hip",
    detail: "Sterile processing forecasts readiness 12 minutes after scheduled incision.",
    recommendation: "Advance sterile processing courier pickup or push incision to 12:42.",
  },
  {
    id: "conflict-sc-1",
    hospitalSlug: "st-catherine-west",
    severity: "High",
    title: "Fetal monitoring hardware under maintenance",
    detail: "Emergency cesarean section is delayed while biomedical engineering swaps the monitoring hub.",
    recommendation: "Reroute backup monitor from labor and delivery and keep OR 5 on priority clean.",
  },
  {
    id: "conflict-sc-2",
    hospitalSlug: "st-catherine-west",
    severity: "Medium",
    title: "Neuro overrun compresses afternoon add-on capacity",
    detail: "Room 1’s active case is trending longer than predicted, jeopardizing the VP shunt revision.",
    recommendation: "Shift VP shunt revision to OR 4 after turnover if spine room clears before 12:15.",
  },
]);

const blockTimes = BlockTimeSchema.array().parse([
  {
    id: "block-nh-ortho",
    hospitalSlug: "north-harbor",
    serviceLine: "Orthopedics",
    day: "Thursday",
    owner: "Dr. Asha Raman",
    allocatedHours: 8,
    usedHours: 6.8,
  },
  {
    id: "block-nh-cardiac",
    hospitalSlug: "north-harbor",
    serviceLine: "Cardiac",
    day: "Thursday",
    owner: "Dr. Miguel Alvarez",
    allocatedHours: 10,
    usedHours: 7.4,
  },
  {
    id: "block-sc-neuro",
    hospitalSlug: "st-catherine-west",
    serviceLine: "Neurosurgery",
    day: "Thursday",
    owner: "Dr. Julia Bennett",
    allocatedHours: 9,
    usedHours: 8.2,
  },
  {
    id: "block-sc-womens-health",
    hospitalSlug: "st-catherine-west",
    serviceLine: "Women’s Health",
    day: "Thursday",
    owner: "Dr. Elena Novak",
    allocatedHours: 7,
    usedHours: 5.1,
  },
]);

const waitlist = WaitlistEntrySchema.array().parse([
  {
    id: "wait-nh-1",
    hospitalSlug: "north-harbor",
    patientName: "Noah Fisher",
    procedureName: "Emergency Appendectomy",
    priority: "Emergent",
    requestedWindow: "ASAP",
    reason: "ED escalation",
  },
  {
    id: "wait-nh-2",
    hospitalSlug: "north-harbor",
    patientName: "Claire Mendoza",
    procedureName: "Port Revision",
    priority: "Urgent",
    requestedWindow: "14:00 - 16:00",
    reason: "Device failure",
  },
  {
    id: "wait-sc-1",
    hospitalSlug: "st-catherine-west",
    patientName: "David Kim",
    procedureName: "VP Shunt Revision",
    priority: "Urgent",
    requestedWindow: "12:20 - 15:00",
    reason: "Neurosurgery add-on",
  },
  {
    id: "wait-sc-2",
    hospitalSlug: "st-catherine-west",
    patientName: "Fiona Morgan",
    procedureName: "Emergency Cesarean Section",
    priority: "Emergent",
    requestedWindow: "Immediate",
    reason: "Maternal / fetal escalation",
  },
]);

const preferenceCards = PreferenceCardSchema.array().parse([
  {
    id: "pref-nh-asha",
    hospitalSlug: "north-harbor",
    surgeonId: "surgeon-nh-asha-raman",
    setupNotes: "Wide implant table on surgeon’s left, robotics drape before anesthesia timeout.",
    preferredDevices: ["Robotic Knee Console", "Revision Hip Implant Tray"],
  },
  {
    id: "pref-nh-priya",
    hospitalSlug: "north-harbor",
    surgeonId: "surgeon-nh-priya-desai",
    setupNotes: "Headlight, nerve monitor, and pathology labels pre-positioned before patient enters room.",
    preferredDevices: ["Laparoscopy Tower A"],
  },
  {
    id: "pref-sc-julia",
    hospitalSlug: "st-catherine-west",
    surgeonId: "surgeon-sc-julia-bennett",
    setupNotes: "Navigation cart opposite scrub table; microscope line check before incision.",
    preferredDevices: ["Neuro Navigation Cart", "Mobile C-Arm"],
  },
  {
    id: "pref-sc-elena",
    hospitalSlug: "st-catherine-west",
    surgeonId: "surgeon-sc-elena-novak",
    setupNotes: "Women’s health tray opened after anesthesia sign-in to reduce exposure time.",
    preferredDevices: ["Fetal Monitoring Hub"],
  },
]);

const documents = DocumentRecordSchema.array().parse([
  {
    id: "doc-nh-1",
    hospitalSlug: "north-harbor",
    caseId: "case-nh-1",
    title: "Implant positioning plan",
    type: "Image Set",
    owner: "Orthopedics",
    updatedAt: "06:55",
  },
  {
    id: "doc-nh-2",
    hospitalSlug: "north-harbor",
    caseId: "case-nh-2",
    title: "Perfusion readiness checklist",
    type: "Checklist",
    owner: "Cardiac Service",
    updatedAt: "08:18",
  },
  {
    id: "doc-sc-1",
    hospitalSlug: "st-catherine-west",
    caseId: "case-sc-1",
    title: "Tumor navigation capture",
    type: "Video Snapshot",
    owner: "Neurosurgery",
    updatedAt: "08:27",
  },
  {
    id: "doc-sc-2",
    hospitalSlug: "st-catherine-west",
    caseId: "case-sc-5",
    title: "OB emergency escalation packet",
    type: "Packet",
    owner: "Women’s Health",
    updatedAt: "09:20",
  },
]);

const costCenters = CostCenterSchema.array().parse([
  {
    id: "cost-nh-ortho",
    hospitalSlug: "north-harbor",
    department: "Orthopedics",
    utilizationRate: 94,
    costPerProcedure: 6120,
    revenuePerOrDay: 43800,
  },
  {
    id: "cost-nh-cardiac",
    hospitalSlug: "north-harbor",
    department: "Cardiac",
    utilizationRate: 88,
    costPerProcedure: 11800,
    revenuePerOrDay: 52100,
  },
  {
    id: "cost-sc-neuro",
    hospitalSlug: "st-catherine-west",
    department: "Neurosurgery",
    utilizationRate: 92,
    costPerProcedure: 10400,
    revenuePerOrDay: 49700,
  },
  {
    id: "cost-sc-womens-health",
    hospitalSlug: "st-catherine-west",
    department: "Women’s Health",
    utilizationRate: 78,
    costPerProcedure: 4860,
    revenuePerOrDay: 28900,
  },
]);

const threads = MessageThreadSchema.array().parse([
  {
    id: "thread-nh-1",
    hospitalSlug: "north-harbor",
    topic: "OR 3 emergency insertion",
    roomLabel: "Coordination Hub",
    participants: ["Charge RN", "Scheduler", "Dr. Priya Desai"],
    lastMessage: "Sterile processing confirms OR 5 can absorb the thyroid case at 11:35.",
    unreadCount: 4,
  },
  {
    id: "thread-nh-2",
    hospitalSlug: "north-harbor",
    topic: "Revision hip implant timing",
    roomLabel: "OR 1",
    participants: ["Sterile Processing", "Ava Clark", "Dr. Asha Raman"],
    lastMessage: "Courier has the implant tray and is en route to sterile core.",
    unreadCount: 1,
  },
  {
    id: "thread-sc-1",
    hospitalSlug: "st-catherine-west",
    topic: "OB emergency routing",
    roomLabel: "OR 5",
    participants: ["OB Lead", "Biomed", "Charge RN"],
    lastMessage: "Backup fetal monitoring hub is leaving L&D now.",
    unreadCount: 5,
  },
  {
    id: "thread-sc-2",
    hospitalSlug: "st-catherine-west",
    topic: "Neuro add-on placement",
    roomLabel: "Command Desk",
    participants: ["Scheduler", "Dr. Julia Bennett", "Isaac Porter"],
    lastMessage: "Tentatively holding OR 4 after turnover for the shunt revision.",
    unreadCount: 2,
  },
]);

const overviewMetrics = OverviewMetricSchema.array().parse([
  {
    id: "metric-nh-utilization",
    hospitalSlug: "north-harbor",
    metricKey: "hospital_utilization",
    metricLabel: "Hospital utilization",
    metricValue: 91,
    unit: "percent",
    targetValue: 85,
    trend: "up",
    owner: "OR Command",
    note: "Sustained utilization above baseline target.",
  },
  {
    id: "metric-nh-on-time-starts",
    hospitalSlug: "north-harbor",
    metricKey: "on_time_starts",
    metricLabel: "On-time starts",
    metricValue: 88,
    unit: "percent",
    targetValue: 90,
    trend: "stable",
    owner: "Scheduling",
    note: "Morning ortho block is the main variance source.",
  },
  {
    id: "metric-nh-open-alerts",
    hospitalSlug: "north-harbor",
    metricKey: "open_alerts",
    metricLabel: "Open alerts",
    metricValue: 3,
    unit: "count",
    targetValue: 2,
    trend: "down",
    owner: "Coordination Desk",
    note: "Alert load improving after room rebalance.",
  },
  {
    id: "metric-sc-utilization",
    hospitalSlug: "st-catherine-west",
    metricKey: "hospital_utilization",
    metricLabel: "Hospital utilization",
    metricValue: 86,
    unit: "percent",
    targetValue: 85,
    trend: "up",
    owner: "OR Command",
    note: "Utilization improving with fewer add-on delays.",
  },
  {
    id: "metric-sc-on-time-starts",
    hospitalSlug: "st-catherine-west",
    metricKey: "on_time_starts",
    metricLabel: "On-time starts",
    metricValue: 82,
    unit: "percent",
    targetValue: 90,
    trend: "down",
    owner: "Scheduling",
    note: "Pre-op readiness variability affecting first starts.",
  },
  {
    id: "metric-sc-open-alerts",
    hospitalSlug: "st-catherine-west",
    metricKey: "open_alerts",
    metricLabel: "Open alerts",
    metricValue: 5,
    unit: "count",
    targetValue: 2,
    trend: "down",
    owner: "Coordination Desk",
    note: "Critical notifications remain elevated this shift.",
  },
]);

const integrationSettings = IntegrationSettingSchema.array().parse([
  {
    id: "integration-nh-ehr",
    hospitalSlug: "north-harbor",
    integrationKey: "ehr",
    integrationLabel: "EHR Core",
    vendorName: "Epic",
    status: "Connected",
    baseUrl: "https://north-harbor.ehr.smartor.demo/fhir",
    lastSyncAt: "2026-03-14T06:30:00Z",
    notes: "Primary EHR boundary for surgical scheduling and patient context.",
  },
  {
    id: "integration-nh-patient-messaging",
    hospitalSlug: "north-harbor",
    integrationKey: "patient_messaging",
    integrationLabel: "Patient Messaging",
    vendorName: "Twilio Health",
    status: "Sandbox",
    baseUrl: "https://north-harbor.notify.smartor.demo",
    lastSyncAt: null,
    notes: "Outbound case updates and patient-family communication rails.",
  },
  {
    id: "integration-nh-billing",
    hospitalSlug: "north-harbor",
    integrationKey: "billing",
    integrationLabel: "Billing Pipeline",
    vendorName: "RevCycle Hub",
    status: "Pending",
    baseUrl: null,
    lastSyncAt: null,
    notes: "Charges and authorization data exchange boundary.",
  },
  {
    id: "integration-nh-analytics",
    hospitalSlug: "north-harbor",
    integrationKey: "analytics",
    integrationLabel: "Analytics Warehouse",
    vendorName: "Snowflake",
    status: "Connected",
    baseUrl: "https://north-harbor.analytics.smartor.demo",
    lastSyncAt: "2026-03-14T04:18:00Z",
    notes: "Near-real-time feed for OR utilization and financial reporting.",
  },
  {
    id: "integration-sc-ehr",
    hospitalSlug: "st-catherine-west",
    integrationKey: "ehr",
    integrationLabel: "EHR Core",
    vendorName: "Cerner",
    status: "Sandbox",
    baseUrl: "https://st-catherine-west.ehr.smartor.demo/fhir",
    lastSyncAt: "2026-03-14T03:55:00Z",
    notes: "Primary EHR boundary for surgical scheduling and patient context.",
  },
  {
    id: "integration-sc-patient-messaging",
    hospitalSlug: "st-catherine-west",
    integrationKey: "patient_messaging",
    integrationLabel: "Patient Messaging",
    vendorName: "Twilio Health",
    status: "Sandbox",
    baseUrl: "https://st-catherine-west.notify.smartor.demo",
    lastSyncAt: null,
    notes: "Outbound case updates and patient-family communication rails.",
  },
  {
    id: "integration-sc-billing",
    hospitalSlug: "st-catherine-west",
    integrationKey: "billing",
    integrationLabel: "Billing Pipeline",
    vendorName: "RevCycle Hub",
    status: "Pending",
    baseUrl: null,
    lastSyncAt: null,
    notes: "Charges and authorization data exchange boundary.",
  },
  {
    id: "integration-sc-analytics",
    hospitalSlug: "st-catherine-west",
    integrationKey: "analytics",
    integrationLabel: "Analytics Warehouse",
    vendorName: "Snowflake",
    status: "Connected",
    baseUrl: "https://st-catherine-west.analytics.smartor.demo",
    lastSyncAt: "2026-03-14T04:26:00Z",
    notes: "Near-real-time feed for OR utilization and financial reporting.",
  },
]);

export const smartorFeatureGroups = [
  {
    title: "Scheduling Core",
    description: "OR visibility, drag scheduling, duration estimation, emergency insertion, and block time control.",
    items: [
      "Real-time OR dashboard",
      "Drag-and-drop scheduling",
      "Case duration estimation",
      "Conflict resolution engine",
      "Emergency case integration",
      "Block time management",
    ],
  },
  {
    title: "Clinical Coordination",
    description: "Assignments, pre-op readiness, room turnover, mobile review, notifications, and communication.",
    items: [
      "Surgeon calendar integration",
      "Equipment and resource tracking",
      "Staff scheduling and assignments",
      "Automated notifications",
      "Patient pre-op workflow",
      "Room turnover tracking",
      "Communication hub",
    ],
  },
  {
    title: "Operational Governance",
    description: "Multi-hospital oversight, insurance status, documentation, waitlists, preference cards, and cost reporting.",
    items: [
      "Mobile access",
      "Multi-hospital management",
      "Insurance and authorization tracking",
      "Preference cards management",
      "Case documentation portal",
      "Waitlist management",
      "Cost center tracking",
    ],
  },
] as const;

function average(values: number[]) {
  return Math.round(values.reduce((total, value) => total + value, 0) / values.length);
}

function filterByHospital<T extends { hospitalSlug: string }>(items: T[], hospitalSlug: string) {
  return items.filter((item) => item.hospitalSlug === hospitalSlug);
}

export function getHospitals() {
  return hospitals;
}

export function getHospitalBySlug(hospitalSlug: string) {
  return hospitals.find((hospital) => hospital.slug === hospitalSlug);
}

export function getHospitalDashboardData(
  hospitalSlug: string,
): HospitalDashboardData | null {
  const hospital = getHospitalBySlug(hospitalSlug);

  if (!hospital) {
    return null;
  }

  return {
    hospital,
    rooms: filterByHospital(rooms, hospitalSlug),
    surgeons: filterByHospital(surgeons, hospitalSlug),
    staff: filterByHospital(staff, hospitalSlug),
    equipment: filterByHospital(equipment, hospitalSlug),
    cases: filterByHospital(cases, hospitalSlug),
    notifications: filterByHospital(notifications, hospitalSlug),
    conflicts: filterByHospital(conflicts, hospitalSlug),
    blockTimes: filterByHospital(blockTimes, hospitalSlug),
    waitlist: filterByHospital(waitlist, hospitalSlug),
    preferenceCards: filterByHospital(preferenceCards, hospitalSlug),
    documents: filterByHospital(documents, hospitalSlug),
    costCenters: filterByHospital(costCenters, hospitalSlug),
    threads: filterByHospital(threads, hospitalSlug),
    overviewMetrics: filterByHospital(overviewMetrics, hospitalSlug),
    integrationSettings: filterByHospital(integrationSettings, hospitalSlug),
  };
}

export function getEnterpriseSnapshot() {
  const monitoredCases = cases.filter((caseItem) => caseItem.status !== "Waitlist");
  const emergentCases = cases.filter((caseItem) => caseItem.urgency === "Emergent");

  return {
    hospitals,
    totalOperatingRooms: hospitals.reduce((total, hospital) => total + hospital.orCount, 0),
    networkUtilization: average(hospitals.map((hospital) => hospital.occupancyRate)),
    firstCaseStarts: average(hospitals.map((hospital) => hospital.onTimeStarts)),
    openAlerts: hospitals.reduce((total, hospital) => total + hospital.alertsOpen, 0),
    activeCases: monitoredCases.length,
    emergentCases: emergentCases.length,
    connectedHospitals: hospitals.filter((hospital) => hospital.ehrStatus === "Connected").length,
  };
}

export function getCaseMap(hospitalSlug: string) {
  return Object.fromEntries(
    filterByHospital(cases, hospitalSlug).map((caseItem) => [caseItem.id, caseItem]),
  ) as Record<string, SurgeryCase>;
}

export function getSurgeonMap(hospitalSlug: string) {
  return Object.fromEntries(
    filterByHospital(surgeons, hospitalSlug).map((surgeon) => [surgeon.id, surgeon]),
  ) as Record<string, Surgeon>;
}

export function getStaffMap(hospitalSlug: string) {
  return Object.fromEntries(
    filterByHospital(staff, hospitalSlug).map((member) => [member.id, member]),
  ) as Record<string, StaffMember>;
}

export function getEquipmentMap(hospitalSlug: string) {
  return Object.fromEntries(
    filterByHospital(equipment, hospitalSlug).map((item) => [item.id, item]),
  ) as Record<string, Equipment>;
}

export function getCostCenters(hospitalSlug: string): CostCenter[] {
  return filterByHospital(costCenters, hospitalSlug);
}

export function getDocuments(hospitalSlug: string): DocumentRecord[] {
  return filterByHospital(documents, hospitalSlug);
}

export function getThreads(hospitalSlug: string): MessageThread[] {
  return filterByHospital(threads, hospitalSlug);
}

export function getOverviewMetrics(hospitalSlug: string): OverviewMetric[] {
  return filterByHospital(overviewMetrics, hospitalSlug);
}

export function getIntegrationSettings(hospitalSlug: string): IntegrationSetting[] {
  return filterByHospital(integrationSettings, hospitalSlug);
}

export function getConflicts(hospitalSlug: string): Conflict[] {
  return filterByHospital(conflicts, hospitalSlug);
}

export function getNotifications(hospitalSlug: string): Notification[] {
  return filterByHospital(notifications, hospitalSlug);
}

export function getPreferenceCards(hospitalSlug: string): PreferenceCard[] {
  return filterByHospital(preferenceCards, hospitalSlug);
}

export function getWaitlistEntries(hospitalSlug: string): WaitlistEntry[] {
  return filterByHospital(waitlist, hospitalSlug);
}

export type EnterpriseSnapshot = ReturnType<typeof getEnterpriseSnapshot>;
